<<<<<<< HEAD
# Generated by Django 3.0 on 2019-12-04 13:15
=======
# Generated by Django 2.2.8 on 2019-12-07 14:13
>>>>>>> 2081c79... worked on inseration, works now

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inseration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('images', models.ImageField(max_length=50, upload_to='images/')),
                ('subcategory', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('inserted_at', models.DateTimeField(auto_now_add=True, verbose_name='inserted_at')),
<<<<<<< HEAD
                ('inserter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inserted_object', to=settings.AUTH_USER_MODEL, verbose_name='Inserter')),
=======
                ('inserter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> 2081c79... worked on inseration, works now
            ],
            options={
                'verbose_name': 'Insertion',
                'verbose_name_plural': 'Insertions',
                'ordering': ['-inserted_at'],
            },
        ),
    ]
